global_options:
  build_web_compilers|dart_source_cleanup:
    release_options:
      enabled: false
# Don't minify so we get somewhat more useful stack traces on crashes.
targets:
  $default:
    builders:
      build_web_compilers|entrypoint:
        options:
          dart2js_args: []
          # - --no-minify
