import "../../hues.dart";
import "help_dialog.dart";

const Map<String, List<HelpLine>> helpChapters = {
  "Quick Reference": [
    HelpLine(color: UIHue.header, "Quick Reference"),
    HelpLine(color: UIHue.header, "════════════════════════════════════════════════════════"),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Movement"),
    HelpLine(color: UIHue.header, "────────────────────────────────────────────────────────"),
    HelpLine("There are two sets of direction keys:"),
    HelpLine(""),
    HelpLine("They can be combined with modifier keys like so:"),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Other commands"),
    HelpLine(color: UIHue.header, "────────────────────────────────────────────────────────"),
  ],
  "Getting Started": [
    HelpLine(color: UIHue.header, "Getting Started"),
    HelpLine(color: UIHue.header, "════════════════════════════════════════════════════════"),
    HelpLine("TODO: This is all horrendously out of date."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("Welcome! If you are here, you must have an adventurous"),
    HelpLine(""),
    HelpLine("spirit. Not only because you wish to venture into"),
    HelpLine(""),
    HelpLine("dungeons filled with beasts and untolds horrors, but"),
    HelpLine(""),
    HelpLine("because you have the fortitude to try out a game while"),
    HelpLine(""),
    HelpLine("it's still under development. A caution for the unwary:"),
    HelpLine(""),
    HelpLine("The game is not done, or balanced, or complete, or"),
    HelpLine(""),
    HelpLine("bug-free. It may destroy your savefiles or steal your"),
    HelpLine(""),
    HelpLine("boyfriend!"),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Input"),
    HelpLine(color: UIHue.header, "────────────────────────────────────────────────────────"),
    HelpLine("Hauberk is played using your keyboard, the fixie of"),
    HelpLine(""),
    HelpLine("input devices. A lot of input is directional. Arrow keys"),
    HelpLine(""),
    HelpLine("work for that, but don't support diagonal moves."),
    HelpLine(""),
    HelpLine("Instead, you're better off hitting num lock and using"),
    HelpLine(""),
    HelpLine("the numpad on your keyboard if you have one:"),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(".---.---.---.          .---.---.---."),
    HelpLine("| 7 | 8 | 9 |          | \\ | ^ | / |"),
    HelpLine("|---+---+---|          |---+---+---|"),
    HelpLine("| 4 | 5 | 6 | maps to: |<- |   | ->|"),
    HelpLine("|---+---+---|          |---+---+---|"),
    HelpLine("| 1 | 2 | 3 |          | / | v | \\ |"),
    HelpLine("'---'---'---'          '---'---'---'"),
    HelpLine(""),
    HelpLine(""),
    HelpLine("If you don't have a numpad, but do have a US layout"),
    HelpLine(""),
    HelpLine("keyboard, you can also use:"),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(".---.---.---.          .---.---.---."),
    HelpLine("| I | O | P |          | \\ | ^ | / |"),
    HelpLine("'---+---+---+          '---+---+---+"),
    HelpLine(" | K | L | ; | maps to: |<- |   | ->|"),
    HelpLine(" '---+---+---+          '---+---+---+"),
    HelpLine("  | , | . | / |          | / | v | \\ |"),
    HelpLine("  '---'---'---'          '---'---'---'"),
    HelpLine(""),
    HelpLine(""),
    HelpLine("The 5 and L buttons in the middle are \"stand\". They're"),
    HelpLine(""),
    HelpLine("also used like an \"OK\" button to accept a selection on"),
    HelpLine(""),
    HelpLine("menu screens. Escape is used to go back in menu screens"),
    HelpLine(""),
    HelpLine("and exit dialogs."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("(Note that all keys are shown uppercase here but are"),
    HelpLine(""),
    HelpLine("typed lower case. L means a lowercase \"l\". An"),
    HelpLine(""),
    HelpLine("uppercase one will be Shift-L.)"),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("At some point, I plan to add support for user-defined"),
    HelpLine(""),
    HelpLine("keybindings, but they aren't there yet."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "A Hero Awakens"),
    HelpLine(color: UIHue.header, "────────────────────────────────────────────────────────"),
    HelpLine("To play, you need an avatar in the game world to live"),
    HelpLine(""),
    HelpLine("(and die!) vicariously through. On the Main Menu Screen,"),
    HelpLine(""),
    HelpLine("type N to create a new hero (or heroine, the game is"),
    HelpLine(""),
    HelpLine("gender-blind). Enter a name, or use the default"),
    HelpLine(""),
    HelpLine("suggested one and hit Enter."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("There isn't much to specify at character creation time"),
    HelpLine(""),
    HelpLine("right now, but eventually you'll pick a class, race, pet"),
    HelpLine(""),
    HelpLine("peeves, favorite sandwich, etc. Currently, warrior is"),
    HelpLine(""),
    HelpLine("the only class."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("Your hero is saved in your browser's local storage. This"),
    HelpLine(""),
    HelpLine("means you can return to the game later and your hero"),
    HelpLine(""),
    HelpLine("will still be there. If you switch browsers, though,"),
    HelpLine(""),
    HelpLine("your heroes won't be in the new browser. Heroes are"),
    HelpLine(""),
    HelpLine("saved every time you leave a level, or exit your home."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("The game is not saved while you're in the middle of a"),
    HelpLine(""),
    HelpLine("level! If you close your browser in the middle of"),
    HelpLine(""),
    HelpLine("playing because your boss walked in, your progress in"),
    HelpLine(""),
    HelpLine("the level will be lost. That's what you get for slacking"),
    HelpLine(""),
    HelpLine("off at work."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("Because the game is still in active development, new"),
    HelpLine(""),
    HelpLine("releases may not be savefile compatible with previous"),
    HelpLine(""),
    HelpLine("ones. Your heroes may get deleted if they don't work"),
    HelpLine(""),
    HelpLine("with the latest code. Sorry."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "The hero screen"),
    HelpLine(""),
    HelpLine("Once you create or choose a hero, you're taken to the"),
    HelpLine(""),
    HelpLine("hero screen. This is sort of like the \"town\" in other"),
    HelpLine(""),
    HelpLine("games. It's the safe place where you can tinker with"),
    HelpLine(""),
    HelpLine("your gear and enter the game."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Your home"),
    HelpLine(""),
    HelpLine("From the hero screen, press H to enter your home. This"),
    HelpLine(""),
    HelpLine("gives you a place where you can stash loot you don't"),
    HelpLine(""),
    HelpLine("want to carry around. You can also move items between"),
    HelpLine(""),
    HelpLine("your inventory (stuff you carry in your backpack) and"),
    HelpLine(""),
    HelpLine("your equipment (weapons and armor you are currently"),
    HelpLine(""),
    HelpLine("wearing or holding)."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "The crucible"),
    HelpLine(""),
    HelpLine("The most interesting facet of your home is the crucible."),
    HelpLine(""),
    HelpLine("This is the place where you can craft—make new items"),
    HelpLine(""),
    HelpLine("from existing ones. You place items into the crucible"),
    HelpLine(""),
    HelpLine("just like you can your home or inventory. However, it"),
    HelpLine(""),
    HelpLine("only allows items that are part of a recipe."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("A recipe is a set of items that can be turned into"),
    HelpLine(""),
    HelpLine("something else. When you place all of the required items"),
    HelpLine(""),
    HelpLine("for a recipe in the crucible, it will tell you. Press"),
    HelpLine(""),
    HelpLine("Space and it will magically transmute them into"),
    HelpLine(""),
    HelpLine("something new."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("The set of recipes is still highly in flux, but try"),
    HelpLine(""),
    HelpLine("dropping a few healing potions in there."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "The Dungeon Awaits"),
    HelpLine(color: UIHue.header, "────────────────────────────────────────────────────────"),
    HelpLine("Now that your hero is alive and ready, it's time to slay"),
    HelpLine(""),
    HelpLine("some beasts."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Areas and levels"),
    HelpLine(""),
    HelpLine("Unlike other roguelikes, Hauberk doesn't have a single"),
    HelpLine(""),
    HelpLine("monolithic dungeon. Instead, there are a number of"),
    HelpLine(""),
    HelpLine("areas. Each area has its own \"flavor\"—it's own kinds"),
    HelpLine(""),
    HelpLine("of monsters, difficulty, appearance, etc. An area is in"),
    HelpLine(""),
    HelpLine("turn divided into a series of levels, each more"),
    HelpLine(""),
    HelpLine("difficult than the last."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("From the hero screen, you can select which area and"),
    HelpLine(""),
    HelpLine("level you want to play. You can only enter an area if"),
    HelpLine(""),
    HelpLine("you've beaten at least one level from the previous area."),
    HelpLine(""),
    HelpLine("Likewise, you must beat a level to unlock the next one."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("Since you just created a hero, you can only play the"),
    HelpLine(""),
    HelpLine("first level of the Friendly Forest, so just type L to"),
    HelpLine(""),
    HelpLine("enter it. Later, when you unlock stuff, use the"),
    HelpLine(""),
    HelpLine("directional keys to select an area and level. You can"),
    HelpLine(""),
    HelpLine("replay a level as many times as you want."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Quests, victory, and defeat"),
    HelpLine(""),
    HelpLine("Every level is randomly generated (of course) and"),
    HelpLine(""),
    HelpLine("populated with monsters and treasure. Each level also"),
    HelpLine(""),
    HelpLine("has a quest. This is a goal you must fulfill before"),
    HelpLine(""),
    HelpLine("you're allowed to leave the level. After completing the"),
    HelpLine(""),
    HelpLine("quest, type Q to leave the level and return to the"),
    HelpLine(""),
    HelpLine("safety of your home. All experience and items gained in"),
    HelpLine(""),
    HelpLine("the level will be saved henceforth and forever more."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("If you die in the level, you lose everything you gained"),
    HelpLine(""),
    HelpLine("while in that level. It isn't quite permadeath, but it's"),
    HelpLine(""),
    HelpLine("pretty damn annoying to lose that experience and"),
    HelpLine(""),
    HelpLine("whatever hot loot you picked up."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("If you want to give up and leave the level before"),
    HelpLine(""),
    HelpLine("completing the quest, you can forfeit by typing Shift-F."),
    HelpLine(""),
    HelpLine("Like dying, doing this sacrifices anything you've gained"),
    HelpLine(""),
    HelpLine("since entering the level."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Navigating the level"),
    HelpLine(""),
    HelpLine("Your avatar in the game is represented by a @. Floor"),
    HelpLine(""),
    HelpLine("tiles are usually ., and impassible barriers and walls"),
    HelpLine(""),
    HelpLine("look like #, or other hopefully obvious solid looking"),
    HelpLine(""),
    HelpLine("tiles."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("You walk around using the directional keys. Pressing the"),
    HelpLine(""),
    HelpLine("stand key (5 or L) makes you stand still for a turn."),
    HelpLine(""),
    HelpLine("That's useful to let a monster take a step closer so you"),
    HelpLine(""),
    HelpLine("can attack the next turn."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("Hold down Shift and press a direction to run in that"),
    HelpLine(""),
    HelpLine("direction. You will repeatedly walk in that direction"),
    HelpLine(""),
    HelpLine("until disturbed by reaching an obstacle, a fork in the"),
    HelpLine(""),
    HelpLine("path, or seeing a monster. When not in combat, running"),
    HelpLine(""),
    HelpLine("is the most user-friendly way to get from point A to"),
    HelpLine(""),
    HelpLine("point B."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("Closed doors look like +. You can open them (which takes"),
    HelpLine(""),
    HelpLine("a turn) by simply walking into them. An open door looks"),
    HelpLine(""),
    HelpLine("like -. You can close a door by pressing C while"),
    HelpLine(""),
    HelpLine("standing next to one."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Combat!"),
    HelpLine(""),
    HelpLine("Monsters in the game are represented using letters. You"),
    HelpLine(""),
    HelpLine("attack by trying to walk into the tile where a monster"),
    HelpLine(""),
    HelpLine("is standing. On the right side of the screen you can see"),
    HelpLine(""),
    HelpLine("your health along with some of the nearby monsters. Try"),
    HelpLine(""),
    HelpLine("to get theirs to zero before yours does!"),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("When you kill a monster, you are granted some experience"),
    HelpLine(""),
    HelpLine("points. Earn enough of those, and your hero will"),
    HelpLine(""),
    HelpLine("increase in experience level. That increases your"),
    HelpLine(""),
    HelpLine("maximum health and does some other good stuff."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("Meanwhile, monsters will be attacking you. You are"),
    HelpLine(""),
    HelpLine("outnumbered, so try not to let them surround you."),
    HelpLine(""),
    HelpLine("Attacking from the safety of a narrow corridor helps."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Resting"),
    HelpLine(""),
    HelpLine("After a skirmish, your hero has likely lost some health."),
    HelpLine(""),
    HelpLine("That can be regained by imbibing magic potions, but"),
    HelpLine(""),
    HelpLine("those are in short supply. Instead, they'll have to"),
    HelpLine(""),
    HelpLine("rest."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("Resting requires food, which you automatically discover"),
    HelpLine(""),
    HelpLine("as you explore the level. Every turn that you stand"),
    HelpLine(""),
    HelpLine("still consumes a bit of food and regains a point of"),
    HelpLine(""),
    HelpLine("health. Instead of mashing down the stand key, if you"),
    HelpLine(""),
    HelpLine("press Shift-Stand, you will repeatedly rest until you"),
    HelpLine(""),
    HelpLine("run out of food, fully regain their health, or are"),
    HelpLine(""),
    HelpLine("disturbed by a nearby monster."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("If you don't have any food, resting accomplishes"),
    HelpLine(""),
    HelpLine("nothing. To get food, you must explore new parts of the"),
    HelpLine(""),
    HelpLine("level. No resting on your laurels or wandering through"),
    HelpLine(""),
    HelpLine("familiar passages!"),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Loot!"),
    HelpLine(""),
    HelpLine("While the ridding the world of an evil beast is its own"),
    HelpLine(""),
    HelpLine("reward, it's not the only reward. Many monsters drop"),
    HelpLine(""),
    HelpLine("treasure, and you'll find some laying on the ground as"),
    HelpLine(""),
    HelpLine("well. Different levels and monsters tend to drop"),
    HelpLine(""),
    HelpLine("different stuff, so explore (and murder) widely."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("Items are represented using punctuation characters."),
    HelpLine(""),
    HelpLine("Potions are !, scrolls are ?, etc. You can pick up an"),
    HelpLine(""),
    HelpLine("item off the ground by standing on top of it and"),
    HelpLine(""),
    HelpLine("pressing G, for \"get\"."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("If there are multiple items in the same tile, that picks"),
    HelpLine(""),
    HelpLine("up the top one. Press G repeatedly to pick them all up."),
    HelpLine(""),
    HelpLine("Eventually, I'll add a menu to let you pick which one"),
    HelpLine(""),
    HelpLine("you want."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("Many items can be used. Potions can be quaffed, scrolls"),
    HelpLine(""),
    HelpLine("read, wands... uh... waved around? To use an item, press"),
    HelpLine(""),
    HelpLine("U to bring up the item selection screen. In addition to"),
    HelpLine(""),
    HelpLine("your inventory and equipment, you can also use items"),
    HelpLine(""),
    HelpLine("that are laying on the ground under you. You don't have"),
    HelpLine(""),
    HelpLine("to pick them up first. (And not picking them up first"),
    HelpLine(""),
    HelpLine("saves you a turn. Useful in the heat of battle!)"),
    HelpLine(""),
    HelpLine("Pressing Tab on the item screen cycles through these"),
    HelpLine(""),
    HelpLine("three views."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("Type the letter next to an item to use it. If the item"),
    HelpLine(""),
    HelpLine("has an active \"use\" like a potion, this will perform"),
    HelpLine(""),
    HelpLine("it. \"Using\" a piece of equipment equips it. Using a"),
    HelpLine(""),
    HelpLine("piece of equipment that you're already wearing unequips"),
    HelpLine(""),
    HelpLine("it. Remember that equipment must be worn to get any"),
    HelpLine(""),
    HelpLine("advantage! Carrying around a sword in your backpack"),
    HelpLine(""),
    HelpLine("doesn't do you much good."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("If you want to discard an item, press D, then select the"),
    HelpLine(""),
    HelpLine("item. It will drop onto the ground. It may gaze back at"),
    HelpLine(""),
    HelpLine("you forlornly, wondering why it wasn't good enough and"),
    HelpLine(""),
    HelpLine("why you love the other items in your inventory more."),
    HelpLine(""),
    HelpLine(""),
    HelpLine(""),
    HelpLine("A more entertaining and often more useful way to rid"),
    HelpLine(""),
    HelpLine("yourself of an item is to throw it, which is done by"),
    HelpLine(""),
    HelpLine("pressing T. Throwing an item at a monster will often"),
    HelpLine(""),
    HelpLine("harm it, and some items do fun and exciting things like"),
    HelpLine(""),
    HelpLine("explode when lobbed at an unsuspecting beastie."),
    HelpLine(""),
  ],
};
