import "../../hues.dart";
import "help_dialog.dart";

const Map<String, List<HelpLine>> helpChapters = {
  "Quick Reference": [
    HelpLine(color: UIHue.header, "Quick Reference"),
    HelpLine(color: UIHue.header, "══════════════════════════════════════════════════"),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Movement"),
    HelpLine(color: UIHue.header, "──────────────────────────────────────────────────"),
    HelpLine(""),
    HelpLine("There are two sets of direction keys:"),
    HelpLine(""),
    HelpLine("<table> <tr> <td> <code>I</code> <code>O</code>"),
    HelpLine("<code>P</code><br> <code>K</code>"),
    HelpLine("<code>&nbsp;</code> <code>;</code><br>"),
    HelpLine("<code>,</code> <code>.</code> <code>/</code><br>"),
    HelpLine("</td> <td> <code>7</code> <code>8</code>"),
    HelpLine("<code>9</code><br> <code>4</code>"),
    HelpLine("<code>&nbsp;</code> <code>6</code><br>"),
    HelpLine("<code>1</code> <code>2</code> <code>3</code><br>"),
    HelpLine("</td> </tr> </table>"),
    HelpLine(""),
    HelpLine("They can be combined with modifier keys like so:"),
    HelpLine(""),
    HelpLine("<table width=\"100%\"> <tr>"),
    HelpLine("<td><code>Direction</code></td><td>Walk one step"),
    HelpLine("in direction, attack adjacent monster</td>"),
    HelpLine("</tr><tr>"),
    HelpLine("<td><code>Shift-Direction</code></td><td>Run in"),
    HelpLine("direction until disturbed</td> </tr><tr>"),
    HelpLine("<td><code>Alt-Direction</code></td><td>Use last"),
    HelpLine("command in that direction</td> </tr> </table>"),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Other commands"),
    HelpLine(color: UIHue.header, "──────────────────────────────────────────────────"),
    HelpLine(""),
    HelpLine("<table width=\"100%\"> <tr> <td><code>L</code>,"),
    HelpLine("<code>Numpad-5</code>,"),
    HelpLine("<code>Enter</code></td><td>Rest one turn, select"),
    HelpLine("menu item</td> </tr><tr> <td><code>Shift-L</code>,"),
    HelpLine("<code>Shift-Numpad-5</code></td><td>Rest until"),
    HelpLine("fully healed or disturbed</td> </tr><tr>"),
    HelpLine("<td><code>C</code></td><td>Close door</td>"),
    HelpLine("</tr><tr> <td><code>U</code></td><td>Use item</td>"),
    HelpLine("</tr><tr> <td><code>D</code></td><td>Drop"),
    HelpLine("item</td> </tr><tr>"),
    HelpLine("<td><code>T</code></td><td>Throw item</td>"),
    HelpLine("</tr><tr>"),
    HelpLine("<td><code>X</code></td><td>Swap&mdash;re-equip"),
    HelpLine("last unequipped item</td> </tr><tr>"),
    HelpLine("<td><code>Q</code></td><td>Exit level after"),
    HelpLine("finishing quest</td> </tr><tr>"),
    HelpLine("<td><code>Shift-F</code></td><td>Forfeit"),
    HelpLine("level</td> </tr> </table>"),
  ],
  "Getting Started": [
    HelpLine(color: UIHue.header, "Getting Started"),
    HelpLine(color: UIHue.header, "══════════════════════════════════════════════════"),
    HelpLine(""),
    HelpLine("TODO: This is all horrendously out of date."),
    HelpLine(""),
    HelpLine("Welcome! I see you have an adventurous spirit! Not"),
    HelpLine("because you wish to venture into dungeons filled"),
    HelpLine("with beasts and untolds horrors, but because you"),
    HelpLine("have the fortitude to try out a game while it's"),
    HelpLine("still under development. Well, some of the former"),
    HelpLine("too."),
    HelpLine(""),
    HelpLine("A caution for the unwary: The game is not done, or"),
    HelpLine("balanced, or complete, or bug-free. It may destroy"),
    HelpLine("your savefiles or steal your boyfriend!"),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Input"),
    HelpLine(color: UIHue.header, "──────────────────────────────────────────────────"),
    HelpLine(""),
    HelpLine("Hauberk is played using your keyboard, the fixie"),
    HelpLine("of input devices. A lot of input is directional."),
    HelpLine("Arrow keys work for that, but don't support"),
    HelpLine("diagonal moves. Instead, you're better off hitting"),
    HelpLine("num lock and using the numpad on your keyboard if"),
    HelpLine("you have one:"),
    HelpLine(""),
    HelpLine(".---.---.---. .---.---.---. | 7 | 8 | 9 | | \ | ^"),
    HelpLine("| / | |---+---+---| |---+---+---| | 4 | 5 | 6 |"),
    HelpLine("maps to: |<- | | ->| |---+---+---| |---+---+---| |"),
    HelpLine("1 | 2 | 3 | | / | v | \ | '---'---'---'"),
    HelpLine("'---'---'---'"),
    HelpLine(""),
    HelpLine("If you don't have a numpad, but do have a US"),
    HelpLine("layout keyboard, you can also use:"),
    HelpLine(""),
    HelpLine(".---.---.---. .---.---.---. | I | O | P | | \ | ^"),
    HelpLine("| / | '---+---+---+ '---+---+---+ | K | L | ; |"),
    HelpLine("maps to: |<- | | ->| '---+---+---+ '---+---+---+ |"),
    HelpLine(", | . | / | | / | v | \ | '---'---'---'"),
    HelpLine("'---'---'---'"),
    HelpLine(""),
    HelpLine("The 5 and L buttons in the middle are \"stand\"."),
    HelpLine("They're also used like an \"OK\" button to accept"),
    HelpLine("a selection on menu screens. Escape is used to go"),
    HelpLine("back in menu screens and exit dialogs."),
    HelpLine(""),
    HelpLine("(Note that all keys are shown uppercase here but"),
    HelpLine("are typed lower case. L means a lowercase \"l\"."),
    HelpLine("An uppercase one will be Shift-L.)"),
    HelpLine(""),
    HelpLine("At some point, I plan to add support for"),
    HelpLine("user-defined keybindings, but they aren't there"),
    HelpLine("yet."),
    HelpLine(""),
    HelpLine(color: UIHue.header, "A Hero Awakens"),
    HelpLine(color: UIHue.header, "──────────────────────────────────────────────────"),
    HelpLine(""),
    HelpLine("To play, you need an avatar in the game world to"),
    HelpLine("live (and die!) vicariously through. On the Main"),
    HelpLine("Menu Screen, type N to create a new hero (or"),
    HelpLine("heroine, the game is gender-blind). Enter a name,"),
    HelpLine("or use the default suggested one and hit Enter."),
    HelpLine(""),
    HelpLine("There isn't much to specify at character creation"),
    HelpLine("time right now, but eventually you'll pick a"),
    HelpLine("class, race, pet peeves, favorite sandwich, etc."),
    HelpLine("Currently, warrior is the only class."),
    HelpLine(""),
    HelpLine("Your hero is saved in your browser's local"),
    HelpLine("storage. This means you can return to the game"),
    HelpLine("later and your hero will still be there. If you"),
    HelpLine("switch browsers, though, your heroes won't be in"),
    HelpLine("the new browser. Heroes are saved every time you"),
    HelpLine("leave a level, or exit your home."),
    HelpLine(""),
    HelpLine("The game is not saved while you're in the middle"),
    HelpLine("of a level! If you close your browser in the"),
    HelpLine("middle of playing because your boss walked in,"),
    HelpLine("your progress in the level will be lost. That's"),
    HelpLine("what you get for slacking off at work."),
    HelpLine(""),
    HelpLine("Because the game is still in active development,"),
    HelpLine("new releases may not be savefile compatible with"),
    HelpLine("previous ones. Your heroes may get deleted if they"),
    HelpLine("don't work with the latest code. Sorry."),
    HelpLine(""),
    HelpLine(color: UIHue.header, "The hero screen"),
    HelpLine(""),
    HelpLine("Once you create or choose a hero, you're taken to"),
    HelpLine("the hero screen. This is sort of like the \"town\""),
    HelpLine("in other games. It's the safe place where you can"),
    HelpLine("tinker with your gear and enter the game."),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Your home"),
    HelpLine(""),
    HelpLine("From the hero screen, press H to enter your home."),
    HelpLine("This gives you a place where you can stash loot"),
    HelpLine("you don't want to carry around. You can also move"),
    HelpLine("items between your inventory (stuff you carry in"),
    HelpLine("your backpack) and your equipment (weapons and"),
    HelpLine("armor you are currently wearing or holding)."),
    HelpLine(""),
    HelpLine(color: UIHue.header, "The crucible"),
    HelpLine(""),
    HelpLine("The most interesting facet of your home is the"),
    HelpLine("crucible. This is the place where you can"),
    HelpLine("craft—make new items from existing ones. You place"),
    HelpLine("items into the crucible just like you can your"),
    HelpLine("home or inventory. However, it only allows items"),
    HelpLine("that are part of a recipe."),
    HelpLine(""),
    HelpLine("A recipe is a set of items that can be turned into"),
    HelpLine("something else. When you place all of the required"),
    HelpLine("items for a recipe in the crucible, it will tell"),
    HelpLine("you. Press Space and it will magically transmute"),
    HelpLine("them into something new."),
    HelpLine(""),
    HelpLine("The set of recipes is still highly in flux, but"),
    HelpLine("try dropping a few healing potions in there."),
    HelpLine(""),
    HelpLine(color: UIHue.header, "The Dungeon Awaits"),
    HelpLine(color: UIHue.header, "──────────────────────────────────────────────────"),
    HelpLine(""),
    HelpLine("Now that your hero is alive and ready, it's time"),
    HelpLine("to slay some beasts."),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Areas and levels"),
    HelpLine(""),
    HelpLine("Unlike other roguelikes, Hauberk doesn't have a"),
    HelpLine("single monolithic dungeon. Instead, there are a"),
    HelpLine("number of areas. Each area has its own"),
    HelpLine("\"flavor\"—it's own kinds of monsters, difficulty,"),
    HelpLine("appearance, etc. An area is in turn divided into a"),
    HelpLine("series of levels, each more difficult than the"),
    HelpLine("last."),
    HelpLine(""),
    HelpLine("From the hero screen, you can select which area"),
    HelpLine("and level you want to play. You can only enter an"),
    HelpLine("area if you've beaten at least one level from the"),
    HelpLine("previous area. Likewise, you must beat a level to"),
    HelpLine("unlock the next one."),
    HelpLine(""),
    HelpLine("Since you just created a hero, you can only play"),
    HelpLine("the first level of the Friendly Forest, so just"),
    HelpLine("type L to enter it. Later, when you unlock stuff,"),
    HelpLine("use the directional keys to select an area and"),
    HelpLine("level. You can replay a level as many times as you"),
    HelpLine("want."),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Quests, victory, and defeat"),
    HelpLine(""),
    HelpLine("Every level is randomly generated (of course) and"),
    HelpLine("populated with monsters and treasure. Each level"),
    HelpLine("also has a quest. This is a goal you must fulfill"),
    HelpLine("before you're allowed to leave the level. After"),
    HelpLine("completing the quest, type Q to leave the level"),
    HelpLine("and return to the safety of your home. All"),
    HelpLine("experience and items gained in the level will be"),
    HelpLine("saved henceforth and forever more."),
    HelpLine(""),
    HelpLine("If you die in the level, you lose everything you"),
    HelpLine("gained while in that level. It isn't quite"),
    HelpLine("permadeath, but it's pretty damn annoying to lose"),
    HelpLine("that experience and whatever hot loot you picked"),
    HelpLine("up."),
    HelpLine(""),
    HelpLine("If you want to give up and leave the level before"),
    HelpLine("completing the quest, you can forfeit by typing"),
    HelpLine("Shift-F. Like dying, doing this sacrifices"),
    HelpLine("anything you've gained since entering the level."),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Navigating the level"),
    HelpLine(""),
    HelpLine("Your avatar in the game is represented by a @."),
    HelpLine("Floor tiles are usually ., and impassible barriers"),
    HelpLine("and walls look like #, or other hopefully obvious"),
    HelpLine("solid looking tiles."),
    HelpLine(""),
    HelpLine("You walk around using the directional keys."),
    HelpLine("Pressing the stand key (5 or L) makes you stand"),
    HelpLine("still for a turn. That's useful to let a monster"),
    HelpLine("take a step closer so you can attack the next"),
    HelpLine("turn."),
    HelpLine(""),
    HelpLine("Hold down Shift and press a direction to run in"),
    HelpLine("that direction. You will repeatedly walk in that"),
    HelpLine("direction until disturbed by reaching an obstacle,"),
    HelpLine("a fork in the path, or seeing a monster. When not"),
    HelpLine("in combat, running is the most user-friendly way"),
    HelpLine("to get from point A to point B."),
    HelpLine(""),
    HelpLine("Closed doors look like +. You can open them (which"),
    HelpLine("takes a turn) by simply walking into them. An open"),
    HelpLine("door looks like -. You can close a door by"),
    HelpLine("pressing C while standing next to one."),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Combat!"),
    HelpLine(""),
    HelpLine("Monsters in the game are represented using"),
    HelpLine("letters. You attack by trying to walk into the"),
    HelpLine("tile where a monster is standing. On the right"),
    HelpLine("side of the screen you can see your health along"),
    HelpLine("with some of the nearby monsters. Try to get"),
    HelpLine("theirs to zero before yours does!"),
    HelpLine(""),
    HelpLine("When you kill a monster, you are granted some"),
    HelpLine("experience points. Earn enough of those, and your"),
    HelpLine("hero will increase in experience level. That"),
    HelpLine("increases your maximum health and does some other"),
    HelpLine("good stuff."),
    HelpLine(""),
    HelpLine("Meanwhile, monsters will be attacking you. You are"),
    HelpLine("outnumbered, so try not to let them surround you."),
    HelpLine("Attacking from the safety of a narrow corridor"),
    HelpLine("helps."),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Resting"),
    HelpLine(""),
    HelpLine("After a skirmish, your hero has likely lost some"),
    HelpLine("health. That can be regained by imbibing magic"),
    HelpLine("potions, but those are in short supply. Instead,"),
    HelpLine("they'll have to rest."),
    HelpLine(""),
    HelpLine("Resting requires food, which you automatically"),
    HelpLine("discover as you explore the level. Every turn that"),
    HelpLine("you stand still consumes a bit of food and regains"),
    HelpLine("a point of health. Instead of mashing down the"),
    HelpLine("stand key, if you press Shift-Stand, you will"),
    HelpLine("repeatedly rest until you run out of food, fully"),
    HelpLine("regain their health, or are disturbed by a nearby"),
    HelpLine("monster."),
    HelpLine(""),
    HelpLine("If you don't have any food, resting accomplishes"),
    HelpLine("nothing. To get food, you must explore new parts"),
    HelpLine("of the level. No resting on your laurels or"),
    HelpLine("wandering through familiar passages!"),
    HelpLine(""),
    HelpLine(color: UIHue.header, "Loot!"),
    HelpLine(""),
    HelpLine("While the ridding the world of an evil beast is"),
    HelpLine("its own reward, it's not the only reward. Many"),
    HelpLine("monsters drop treasure, and you'll find some"),
    HelpLine("laying on the ground as well. Different levels and"),
    HelpLine("monsters tend to drop different stuff, so explore"),
    HelpLine("(and murder) widely."),
    HelpLine(""),
    HelpLine("Items are represented using punctuation"),
    HelpLine("characters. Potions are !, scrolls are ?, etc. You"),
    HelpLine("can pick up an item off the ground by standing on"),
    HelpLine("top of it and pressing G, for \"get\"."),
    HelpLine(""),
    HelpLine("If there are multiple items in the same tile, that"),
    HelpLine("picks up the top one. Press G repeatedly to pick"),
    HelpLine("them all up. Eventually, I'll add a menu to let"),
    HelpLine("you pick which one you want."),
    HelpLine(""),
    HelpLine("Many items can be used. Potions can be quaffed,"),
    HelpLine("scrolls read, wands... uh... waved around? To use"),
    HelpLine("an item, press U to bring up the item selection"),
    HelpLine("screen. In addition to your inventory and"),
    HelpLine("equipment, you can also use items that are laying"),
    HelpLine("on the ground under you. You don't have to pick"),
    HelpLine("them up first. (And not picking them up first"),
    HelpLine("saves you a turn. Useful in the heat of battle!)"),
    HelpLine("Pressing Tab on the item screen cycles through"),
    HelpLine("these three views."),
    HelpLine(""),
    HelpLine("Type the letter next to an item to use it. If the"),
    HelpLine("item has an active \"use\" like a potion, this"),
    HelpLine("will perform it. \"Using\" a piece of equipment"),
    HelpLine("equips it. Using a piece of equipment that you're"),
    HelpLine("already wearing unequips it. Remember that"),
    HelpLine("equipment must be worn to get any advantage!"),
    HelpLine("Carrying around a sword in your backpack doesn't"),
    HelpLine("do you much good."),
    HelpLine(""),
    HelpLine("If you want to discard an item, press D, then"),
    HelpLine("select the item. It will drop onto the ground. It"),
    HelpLine("may gaze back at you forlornly, wondering why it"),
    HelpLine("wasn't good enough and why you love the other"),
    HelpLine("items in your inventory more."),
    HelpLine(""),
    HelpLine("A more entertaining and often more useful way to"),
    HelpLine("rid yourself of an item is to throw it, which is"),
    HelpLine("done by pressing T. Throwing an item at a monster"),
    HelpLine("will often harm it, and some items do fun and"),
    HelpLine("exciting things like explode when lobbed at an"),
    HelpLine("unsuspecting beastie."),
  ],
};
